### ISSUE TITLE
概要のところのタグが

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi-netlify#10]
概要のところもタグがそのまま使われるっぽいので、h2とかこうなっちゃいます

<img width="402" alt="2017-04-29 13 07 45" src="https://cloud.githubusercontent.com/assets/11687509/25552759/ee0a20c2-2cdc-11e7-8163-1f3c978d2575.png">

**Comment by shimakyohsuke** [comment]
これテーマ側がエスケープしてないんすよね

**Comment by mismith0227** [comment]
CSSでそこにスタイルあてるとか、記事書くルール決めるとかですかね

**Comment by shimakyohsuke** [comment]
#15 で対応
