### ISSUE TITLE
固定ページの除外

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi-netlify#12]
固定ページをリストから除外

ここを直したらいけたのでメモしときます。
https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/master/themes/hugo_theme_robust/layouts/_default/list.html#L14

こんな感じで
```
{{ range $i, $p := (.Paginate (where .Data.Pages "Type" "review")).Pages }}
```

できれば右カラムのLATESTSからも除外したいけど、記事増えてったら自然と消えるだそうしこのままでもいいかも。それか日付操作するか。

あとは、固定ページへのリンクをどこに置くかですかね。
ヘッダーの下とか、右カラムとか？？

**Comment by mismith0227** [comment]
一応これについて書かれてるHugoのドキュメント
https://gohugo.io/extras/pagination/#configuration

**Comment by shimakyohsuke** [comment]
やっときます
