### ISSUE TITLE
誰が書いた記事か表示させたい

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi-netlify#26]

**Comment by shimakyohsuke** [comment]
投稿者を表示させるのは簡単っすけど、投稿者一覧ページみたいなのもいります？

**Comment by mismith0227** [comment]
あった方が、何人かでやってるメディア感出てよいですね。

**Comment by shimakyohsuke** [comment]
一覧はちょっとやり方考えますわー

**Comment by shimakyohsuke** [comment]
とりあえず #27 で投稿者はでます

**Comment by mismith0227** [comment]
マージしやした。

名前クリックしたらTwitterのプロフィールページにリンクするとか、プロフィールページ作ってそこへリンクとか個々のプロフィールをどうするかもまた考えましょう。

**Comment by shimakyohsuke** [comment]
プロフィールページかーなるほどー
今度決めましょうー

**Comment by mismith0227** [comment]
ってか、他の記事もやってくだせえ（笑
名前出すの

**Comment by shimakyohsuke** [comment]
漢字なのかアルファベットなのか英語なのかわからんかったから、各々できめておくれｗ

以下の

https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/master/content/review/tajima.md

```
author = "shimakyohsuke"
```

で出るっす

**Comment by mismith0227** [comment]
とりあえずTwitterのIDでいいと思いますよ。やっときますわ
