### ISSUE TITLE
SNSへのリンク

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi-netlify#29]
とりあえずTwitter、Facebookのアカウントはある。
あとインスタもやるかどうか

**Comment by shimakyohsuke** [comment]
とりいそぎサイドバーにTWのフィード表示でええかな？

**Comment by mismith0227** [comment]
@shimakyohsuke フィード表示どうでしょうね。個人的にはフィード表示あんま好きじゃないんですよね。スマホで見た時スクロールがうっとおしくて。
Twitterアイコンおいてアカウントへリンクぐらいでいいかと思ってたんですが。

**Comment by shimakyohsuke** [comment]
たしかに邪魔だなー

ではアイコンをフッターに置いておくわー

**Comment by mismith0227** [comment]
@shimakyohsuke それで！

**Comment by shimakyohsuke** [comment]
フッターに追加しましたー

**Comment by mismith0227** [comment]
ざっす
