### ISSUE TITLE
consoleで「おっぱい本町」のアスキーアートを出す

### ISSUE THREAD

**Issue by mismith0227** [honmachi-nomi/knp-honmachi-netlify#34]
参考
http://qiita.com/kenzooooo/items/9bc3520215a7d9823608

http://qiita.com/oohira/items/6c30bdf3636a134cf119

**Comment by contiki9** [comment]
アスキーアート化のツール
http://mementoo.info/archives/1773

**Comment by shimakyohsuke** [comment]
絵じゃん

**Comment by shimakyohsuke** [comment]
#55 対応
