### ISSUE TITLE
メンバーページ作る

### ISSUE THREAD

**Issue by contiki9** [honmachi-nomi/knp-honmachi-netlify#40]
メンバーのプロフィールページの作成
HPや好きな食べ物、SNSアカウントなど

**Comment by shimakyohsuke** [comment]
@contiki9 
それぞれブランチきってこのページ更新して
https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/master/content/about.md
PRもらえたら以下に公開されます

http://knp-honmachi.net/about/

**Comment by mismith0227** [comment]
たしかHTMLタグとかclassも使えるからけっこう自由にできるはず

**Comment by shimakyohsuke** [comment]
それか
ttp://knp-honmachi.net/member/
とかメンバーTOP作って以下リンクはるとか
ttp://knp-honmachi.net/member/contiki9/
ttp://knp-honmachi.net/member/mismith0227/
ttp://knp-honmachi.net/member/shima_x_o/

**Comment by shimakyohsuke** [comment]
#41 これ一旦マージするね

**Comment by shimakyohsuke** [comment]
できた
http://knp-honmachi.net/member/

**Comment by mismith0227** [comment]
あ、こんなプルリクあったのか

**Comment by mismith0227** [comment]
あ、今作ったのか

**Comment by shimakyohsuke** [comment]
いや、さっき作った

**Comment by shimakyohsuke** [comment]
index.mdでいけるのか謎だったので

**Comment by shimakyohsuke** [comment]
https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/master/content/member/index.md
ここ編集してPRもらえれば更新できる

**Comment by shimakyohsuke** [comment]
@contiki9 @mismith0227 
#43 適当にやっといたからマージ後、フェッチして適宜更新してくれたまえ

**Comment by mismith0227** [comment]
うぇーい

**Comment by contiki9** [comment]
はあく

**Comment by shimakyohsuke** [comment]
@contiki9 こっちになったので
https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/master/content/about.md

**Comment by contiki9** [comment]
うむ

**Comment by shimakyohsuke** [comment]
いまマージ待ちなのはこんな状態
https://github.com/honmachi-nomi/knp-honmachi-netlify/blob/b89ba6e64fcfa38a922535f8138c0481b9ef500d/content/about.md

**Comment by mismith0227** [comment]
これでええわ

**Comment by shimakyohsuke** [comment]
#43
